# syntax=docker/dockerfile:1
FROM gradle:8.3.0-jdk8 AS build

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/AtsumeruDev/Atsumeru.git .

RUN ./gradlew bootJar

FROM eclipse-temurin:11-jre

RUN mkdir -p /library
RUN mkdir -p /app

COPY --from=build /app/build/libs/*.jar /app/Atsumeru.jar
WORKDIR /app

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPT_PORT} ${JAVA_OPT_XMX} -jar Atsumeru.jar"]

EXPOSE ${JAVA_OPT_PORT}

LABEL org.opencontainers.image.source="https://github.com/AtsumeruDev"
LABEL version="1.0.2"
LABEL description="Free self-hosted mangas/comics/light novels media server"
