# syntax=docker/dockerfile:1
FROM gradle:jdk11 AS build

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/Atsumeru-xyz/Atsumeru.git .

RUN apt-get update && apt-get install -y git

RUN chmod +x gradlew

RUN gradle wrapper

RUN ./gradlew bootJar

FROM eclipse-temurin:11-jre

RUN mkdir -p /library
RUN mkdir -p /app

COPY --from=build /app/build/libs/*.jar /app/Atsumeru.jar
WORKDIR /app

ENTRYPOINT ["sh", "-c", "java -Dserver.port=31337 ${JAVA_OPT_XMX} -jar Atsumeru.jar"]

EXPOSE 31337

HEALTHCHECK --interval=1m --timeout=5s --retries=3 --start-period=1m CMD curl -o /dev/null -s -w "%{http_code}\n" http://localhost:31337/api/server/ping | grep -qE "^[4]" && exit 0 || echo "Atsumeru , blyat, upal!" && exit 1

LABEL org.opencontainers.image.source="https://github.com/Atsumeru-xyz"
LABEL version="1.0.3"
LABEL description="Free self-hosted mangas/comics/light novels media server"
LABEL maintainer="OlegEnot"
