version: '3.3'

networks:
  atsumeru-net:
    driver: bridge

services:
    atsumeru:
        volumes:
            - '/path/to/you/library:/library'
            - '/path/to/atsumeru/config:/app/config'
            - '/path/to/atsumeru/db:/app/database'
            - '/path/to/atsumeru/cache:/app/cache'
            - '/path/to/atsumeru/logs:/app/logs'
        restart: unless-stopped
        image: 'atsumerudev/atsumeru:latest'
        networks:
            - atsumeru-net

    cloudflare-tunnel:
        image: cloudflare/cloudflared
        restart: unless-stopped
        command: 'tunnel --no-autoupdate run --token'
        volumes:
            - /etc/localtime:/etc/localtime:ro
        networks:
            - atsumeru-net
        environment:
            TUNNEL_TOKEN: "<token>"
        depends_on:
            - atsumeru